### ISSUE TITLE
new rds exporter release

### ISSUE THREAD

**Issue by denisok** [percona/rds_exporter#71]
@maxknee asked in #70 about new release

**Comment by denisok** [comment]
@maxknee I don't really see the releases we done. How do you use it and what release?

**Comment by maxknee** [comment]
It looks like you have a github action very similar for this:https://github.com/percona/mongodb_exporter/actions/workflows/release.yml in another project

**Comment by denisok** [comment]
@maxknee ok, so just a bin in a tarball will do it for you?

@percona-csalguero could you please push new tag and new release?

**Comment by maxknee** [comment]
@denisok yep! for linux x86

**Comment by yonahd** [comment]
@denisok If you are creating a release can a new docker image as well?
